### PR TITLE
Tickets/infra 206

### PR DESCRIPTION
**Pull request by hassanxp**
Pull request generated. This is a basis of what I expect to maintain, at least for the short term, for Princeton documents.

### CODE REVIEW

**Comment by himorin** [comment]
if possible, please add one line entry to the top page (to show what is in this repository).

**Comment by hassanxp** [comment]
Of course. Added line describing new Princeton folder as requested.

**Review by himorin — APPROVED** [review]

**Review by yukimoritani — DISMISSED** [review]

**Review by yukimoritani — COMMENTED** [review]
I'm sorry for commenting after I approved it ... but  considering a possibility for other institute to follow you, the folder could be under a sort of folder named "registry" or something... Just an thought

**Comment by hassanxp** [comment]
Good point. So how about changing the folder from `/princeton` to `/registries/princeton` ?

**Review by yukimoritani — APPROVED** [review]

**Pull request merged**
